app/routes.py
from flask import Blueprint, render_template, request, redirect, url_for, session, flash
from sqlalchemy import desc
from flask_login import login_user, logout_user, current_user, login_required
from app.models import Movie, User
from app.forms import RegisterForm, LoginForm, EmailForm, ResetForm
from datetime import datetime, timedelta
from urllib.parse import unquote
from app import db
import app.suggest_algo as suggest_algo
import app.email_sending as email_sending
import app.recovery_passcode as recovery_passcode
from app.few_functions import login_register, interactions

main_bp = Blueprint('main', __name__)

#Routes
#home
@main_bp.route('/', methods = ['POST', 'GET'])
def index(): 
    loginForm, registerForm = login_register()
    keywords = request.args.get('search')
    if keywords:
        return redirect(url_for('main.results', keywords = keywords))
    mostRecent = Movie.query.order_by(desc(Movie.release_date)).limit(16).all()
    mostLiked = Movie.query.order_by(desc(Movie.likes)).limit(16).all()
    mostDisliked = Movie.query.order_by(desc(Movie.dislikes)).limit(16).all()
    return render_template('index.html', registerForm = registerForm, loginForm = loginForm,
                            mostRecent = mostRecent, mostLiked = mostLiked, mostDisliked = mostDisliked)

@main_bp.route('/recovery', methods = ['POST', 'GET'])
def recovery():
    loginForm, registerForm = login_register()
    if 'step' not in session:
        session['step'] = 1
    emailForm = EmailForm()
    resetForm = ResetForm()
    if session['step'] == 1:
        if emailForm.validate_on_submit():
            session['email'] = emailForm.email.data
            user = User.query.filter_by(email=session['email']).first()
            if user:
                code = recovery_passcode.passcode_generation()
                session['code'] = code
                session['expiry_time'] = datetime.now() + timedelta(minutes = 10)
                email_sending.send(code, [emailForm.email.data])
                flash('A recovery code has been sent to your email.', 'info')
                session['step'] = 2
                return redirect(url_for('main.recovery'))
            else:
                flash('Email address is not associated with any account!', 'info')
        return render_template('recovery.html', registerForm = registerForm, loginForm = loginForm, form = emailForm, step = 1)
    elif session['step'] == 2:
        if resetForm.validate_on_submit():
            print(f"Session code: {session.get('code')}")
            print(f"Entered code: {resetForm.code}")
            print(f"Expiry time: {session.get('expiry_time')}")
            if recovery_passcode.passcode_check(session.get('code'), resetForm.code.data) and datetime.now().replace(tzinfo=None) <= session.get('expiry_time').replace(tzinfo=None):
                user = User.query.filter_by(email=session.get('email')).first()
                user.username = resetForm.username.data
                user.password = resetForm.password1.data
                db.session.commit()
                session.clear()
                flash('Account updated!', 'info')
                return redirect(url_for('main.index'))
            else:
                flash('Incorrect or expired recovery code!', 'info')
        return render_template('recovery.html', registerForm = registerForm, loginForm = loginForm, form = resetForm, step = 2)

@main_bp.route('/reset_recovery', methods = ['POST'])
def reset_recovery():
    session.clear()
    return '', 204

@main_bp.route('/logout')
def logout():
    logout_user()
    flash('You have been logged out!', category = 'info')
    return redirect(url_for('main.index'))

@main_bp.route('/results', methods = ['POST', 'GET'])
def results():
    loginForm, registerForm = login_register()
    keywords = request.args.get('search')
    if keywords:
        return redirect(url_for('main.results', keywords = keywords))
    keywords = request.args.get('keywords')
    list = Movie.query.filter(Movie.movie_title.ilike(f"%{keywords}%")).all()
    return render_template('results.html', list = list, registerForm = registerForm, loginForm = loginForm)

#movies
@main_bp.route('/movies', methods = ['POST', 'GET'])
def movies():
    loginForm, registerForm = login_register()
    keywords = request.args.get('search')
    if keywords:
        return redirect(url_for('main.results', keywords = keywords))
    noMovies = 48
    page = request.args.get('page', default = 1, type  = int)
    movieQuery = Movie.query.paginate(page = page, per_page = noMovies, error_out = False)
    start = max(1, page - 5)
    end = min(movieQuery.pages, page + 5)
    return render_template('movies.html',
                            movies = movieQuery.items,
                            curPage = movieQuery.page,
                            next = movieQuery.has_next,
                            prev = movieQuery.has_prev,
                            nextPage = movieQuery.next_num,
                            prevPage = movieQuery.prev_num,
                            noPages = movieQuery.pages,
                            start = start,
                            end = end,
                            registerForm = registerForm, loginForm = loginForm)

#genre
@main_bp.route('/genre/<genre>', methods = ['POST', 'GET'])
def genre(genre):
    loginForm, registerForm = login_register()
    keywords = request.args.get('search')
    if keywords:
        return redirect(url_for('main.results', keywords = keywords))
    noMovies = 48
    page = request.args.get('page', default = 1, type  = int)
    genreList = Movie.query.filter(Movie.genres.ilike(f"%{genre}%")).paginate(page=page, per_page=noMovies, error_out=False)
    start = max(1, page - 5)
    end = min(genreList.pages, page + 5)
    return render_template('genre.html', 
                            genre = genre,
                            movies = genreList.items, 
                            next = genreList.has_next,
                            prev = genreList.has_prev,
                            nextPage = genreList.next_num,
                            prevPage = genreList.prev_num,
                            noPages = genreList.pages,
                            start = start,
                            end = end,
                            registerForm = registerForm, loginForm = loginForm)

#watching
@main_bp.route('/watching/<movie_title>', methods = ['POST', 'GET'])
def watching(movie_title):
    loginForm, registerForm = login_register()
    keywords = request.args.get('search')
    if keywords:
        return redirect(url_for('main.results', keywords = keywords))
    title = unquote(movie_title)
    movie = Movie.query.filter_by(movie_title = title).first()
    path = f"videos/{movie.id}.mp4"
    if not movie:
        return "Movie not found", 404
    list = suggest_algo.suggest(title)
    movies = Movie.query.filter(Movie.movie_title.in_(list)).all()
    return render_template('movie-watching.html', movie = movie, movies = movies, registerForm = registerForm, loginForm = loginForm, path = path)

#movie description
@main_bp.route('/description/<movie_title>', methods = ['POST', 'GET'])
def description(movie_title):
    loginForm, registerForm = login_register()
    keywords = request.args.get('search')
    if keywords:
        return redirect(url_for('main.results', keywords = keywords))
    title = unquote(movie_title)
    movie = Movie.query.filter_by(movie_title = title).first()
    if not movie:
        return "Movie not found", 404
    list = suggest_algo.suggest(title)
    movies = Movie.query.filter(Movie.movie_title.in_(list)).all()
    interaction = interactions(movie)
    if interaction:
        return interaction
    return render_template('movie-description.html', movie = movie, movies = movies, registerForm = registerForm, loginForm = loginForm)

#user library
@main_bp.route('/library', methods = ['POST', 'GET'])
def library():
    library = current_user.movies
    loginForm, registerForm = login_register()
    keywords = request.args.get('search')
    if keywords:
        return redirect(url_for('main.results', keywords = keywords))
    return render_template('library.html', registerForm = registerForm, loginForm = loginForm, library = library)

app/templates/email.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Email recovery</title>
</head>
<body style="font-family: Arial, sans-serif; color: black;">
    <p>Hello,</p> 
    <p>We received a request to recover your account. Please use the following recovery code to recover your account:</p>
    <p>{{ code }}</p>
    <p>To recover your account, enter this code on the recovery page.</p>
    <p>Thanks,</p>
    <p>Group 9</p>
</body>
</html>

app/templates/genre.html
{% extends 'base.html' %}

{% block head %}
<link rel="stylesheet" href="{{ url_for('static', filename = 'home.css')}}" />
<link rel="stylesheet" href="{{ url_for('static', filename = 'base.css')}}" />
<link rel="stylesheet" href="{{ url_for('static', filename = 'movie.css')}}" />
<title>{{ genre }}</title>
{% endblock %}

{% block content %}
<br />
<div class="grid">
    <section class="film-area">
        <div class="film-area__header">
            <h2 class="film-area__title">Genre : {{ genre }}</h2>
            <div class="film-area__tabs"></div>
        </div>
        <div class="grid__row">
            {% for movie in movies %}
            <div class="grid__column-8">
                <a href="" class="film">
                    <div class="film__poster">
                        <div class="film__quality">HD</div>
                        <img src="{{ movie.poster_url }}" alt="{{ movie.movie_title }}" class="film__img" />
                        <a href="{{ url_for('main.watching', movie_title=movie.movie_title|urlencode) }}"
                            title="{{ movie.movie_title }}">
                            <div class="film__play">
                                <i class="fa fa-play"></i>
                            </div>
                        </a>
                    </div>
                    <div class="film__details">
                        <h3 class="film__name">
                            <a href="{{ url_for('main.description', movie_title=movie.movie_title|urlencode) }}"
                                class="film__link" title="{{ movie.movie_title }}">
                                {{ movie.movie_title }}
                            </a>
                        </h3>
                        <div class="film__infor">
                            <div class="film__infor--container">
                                <span class="film__infor--year">
                                    {% if movie.release_date %} {{
                                    movie.release_date.strftime('%Y') }} {% else %} Unknown {%
                                    endif %}
                                </span>
                                <span class="dot"></span>
                                <span class="film__infor--minute">
                                    {% if movie.runtime == 0 %} Unknown {% else %} {{
                                    movie.runtime }} min {% endif %}
                                </span>
                            </div>
                            <span class="film__infor--type">Movie</span>
                        </div>
                    </div>
                </a>
            </div>
            {% endfor %}
        </div>
    </section>
</div>
<div class="pagination">
    {% if prev %}
    <a class="pagination_btn" href="{{ url_for('main.genre', genre = genre, page = prevPage) }}">Previous</a>
    {% endif %} {% for page in range(start, end) %}
    <a href="{{ url_for('main.genre', genre = genre, page = page) }}" class="{% if page == curPage %}active{% endif %} pagination_btn">
        {{ page }}
    </a>
    {% endfor %} {% if next %}
    <a class="pagination_btn" href="{{ url_for('main.genre', genre = genre, page = nextPage) }}">Next</a>
    {% endif %}
</div>
{% endblock %}

app/templates/library.html
{% extends 'base.html' %}

{% block head %}
<link rel="stylesheet" href="{{ url_for('static', filename = 'home.css')}}" />
<link rel="stylesheet" href="{{ url_for('static', filename = 'base.css')}}" />
<title>Library</title>
{% endblock %}

{% block content %}
<br />
<div class="grid">
    {% if current_user.is_authenticated %}
    <section class="film-area">
        <div class="film-area__header">
            <h2 class="film-area__title">Library</h2>
            <div class="film-area__tabs"></div>
        </div>
        <div class="grid__row">
            {% for movie in library %}
            <div class="grid__column-8">
                <a href="" class="film">
                    <div class="film__poster">
                        <div class="film__quality">HD</div>
                        <img src="{{ movie.poster_url }}" alt="{{ movie.movie_title }}" class="film__img" />
                        <a href="{{ url_for('main.watching', movie_title=movie.movie_title|urlencode) }}"
                            title="{{ movie.movie_title }}">
                            <div class="film__play">
                                <i class="fa fa-play"></i>
                            </div>
                        </a>
                    </div>
                    <div class="film__details">
                        <h3 class="film__name">
                            <a href="{{ url_for('main.description', movie_title=movie.movie_title|urlencode) }}"
                                class="film__link" title="{{ movie.movie_title }}">
                                {{ movie.movie_title }}
                            </a>
                        </h3>
                        <div class="film__infor">
                            <div class="film__infor--container">
                                <span class="film__infor--year">
                                    {% if movie.release_date %} {{
                                    movie.release_date.strftime('%Y') }} {% else %} Unknown {%
                                    endif %}
                                </span>
                                <span class="dot"></span>
                                <span class="film__infor--minute">
                                    {% if movie.runtime == 0 %} Unknown {% else %} {{
                                    movie.runtime }} min {% endif %}
                                </span>
                            </div>
                            <span class="film__infor--type">Movie</span>
                        </div>
                    </div>
                </a>
            </div>
            {% endfor %}
        </div>
    </section>
    {% else %}
    <p>Log in to access library feature</p>
    {% endif %}
</div>
{% endblock %}

app/templates/movie-description.html
{% extends 'base.html' %}

{% block head %}
<title>Movie Description</title>
<link rel="stylesheet" href="{{ url_for('static', filename = 'movie-description.css')}}" />
{% endblock %}

{% block content %}
<div class="content">
    <div class="prebread">
        <li class="prelist">
            <a href="{{ url_for('main.index')}}" title="Home">Home /</a>
        </li>
        <li class="prelist">
            <a href="{{ url_for('main.movies')}}" title="Movies">Movies /</a>
        </li>
        {% set name = movie.movie_title %}
        <li class="prelist">
            <a href="{{ url_for('main.description', movie_title=movie.movie_title|urlencode) }}" title="{{ movie.movie_title }}">{{ movie.movie_title }}</a>
        </li>
    </div>
    <div class="cover_img"
        style="background-image: url('{{ movie.backdrop_path }}');">
    </div>
    <div class="container grid">

        <div class="kolmj">
            <a href="{{ url_for('main.watching', movie_title=movie.movie_title|urlencode) }}" class="d_play">
                <i class="fa fa-play"></i></a>
        </div>
        <div class="details__khung"> 
            <div class="details__left">
                <div class="details__poster">
                    <img style="border-radius: 10px; width: 178px; height: 268px;" src="{{ movie.poster_url }}" alt="">
                </div>
                <div class="details__vote" id="movie-reactions">Likes: {{ movie.likes }} | Dislikes {{ movie.dislikes }}</div>
                <button class="details__like" id="like" action="like" data-movie-title="{{ movie.movie_title|urlencode }}" state = "{{ current_user.is_authenticated }}"><i class="fa-solid fa-thumbs-up"></i> Like</button>
                <button class="details__dislike" id="dislike" action="dislike" data-movie-title="{{ movie.movie_title|urlencode }}" state = "{{ current_user.is_authenticated }}"><i class="fa-solid fa-thumbs-down"></i> Dislike</button>
            </div>
            <div class="details__right">
                <div class="details__watch">
                    <button class="details__watchnow" onclick="window.location.href='{{ url_for('main.watching', movie_title=movie.movie_title|urlencode) }}'; return false;" title="Watch now"><i class="fa-solid fa-play"></i>        Watch now</button>
                    {% if current_user.is_authenticated and movie in current_user.movies %}
                        {% set libraryButtonAction = 'remove' %}
                        {% set libraryButtonText = 'Remove from library' %}
                    {% else %}
                        {% set libraryButtonAction = 'add' %}
                        {% set libraryButtonText = 'Add to library' %}
                    {% endif %}
                    <button class="details__add" id="libraryButton" action="{{ libraryButtonAction }}" data-movie-title="{{ movie.movie_title|urlencode }}" state = "{{ current_user.is_authenticated }}"><i class="fa-solid fa-plus"></i> {{ libraryButtonText }}</button>
                </div>
                <h2 class="details__heading-name">{{ movie.movie_title }}</h2>
                <div class="details__description">{{ movie.overview }}</div>
                <div class="details__elements">
                    <div id="details__element1">
                            <div><b>Released:</b> {{ movie.release_date }}</div>
                            <div><b>Genre:</b> {{ movie.genres }}</div>
                            <div><b>Casts:</b> {{ movie.actor_1_name }}  ,  {{ movie.actor_2_name }}  ,  {{ movie.actor_3_name }}</div>
                        </ul>
                    </div>
                    <div id="details__element2">
                            <div><b>Duration:</b> {{ movie.runtime}} min</div>
                            <div><b>Country:</b> {{ movie.origin_country }}</div>
                            <div><b>Production:</b> {{ movie.production }}
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script src="{{ url_for('static', filename = 'DescriptionButtons.js')}}"></script>
<br>
<div class="grid">
    <section class="film-area">
      <div class="film-area__header">
        <h2 class="film-area__title">You may also like</h2>
        <div class="film-area__tabs"></div>
      </div>
      <div class="grid__row">
        {% for movie in movies %}
        <div class="grid__column-8">
          <a href="" class="film">
            <div class="film__poster">
              <div class="film__quality">HD</div>
              <img src="{{ movie.poster_url }}" alt="{{ movie.movie_title }}" class="film__img" />
              <a href="{{ url_for('main.watching', movie_title=movie.movie_title|urlencode) }}"
                title="{{ movie.movie_title }}">
                <div class="film__play">
                  <i class="fa fa-play"></i>
                </div>
              </a>
            </div>
            <div class="film__details">
              <h3 class="film__name">
                <a href="{{ url_for('main.description', movie_title=movie.movie_title|urlencode) }}"
                  class="film__link" title="{{ movie.movie_title }}">
                  {{ movie.movie_title }}
                </a>
              </h3>
              <div class="film__infor">
                <div class="film__infor--container">
                  <span class="film__infor--year">
                    {% if movie.release_date %} {{
                    movie.release_date.strftime('%Y') }} {% else %} Unknown {%
                    endif %}
                  </span>
                  <span class="dot"></span>
                  <span class="film__infor--minute">
                    {% if movie.runtime == 0 %} Unknown {% else %} {{
                    movie.runtime }} min {% endif %}
                  </span>
                </div>
                <span class="film__infor--type">Movie</span>
              </div>
            </div>
          </a>
        </div>
        {% endfor %}
      </div>
    </section>
  </div>
{% endblock %}

app/templates/movie-watching.html
{% extends 'base.html' %} {% block head %}
<title>Watching</title>
<link
  rel="stylesheet"
  href="{{ url_for('static', filename = 'movie-watching.css')}}"
/>
{% endblock %} {% block content %}
<br />
<div class="vd-prebread">
  <li class="vd-prelist">
    <a href="{{ url_for('main.index')}}" title="Home">Home /</a>
  </li>
  <li class="vd-prelist">
    <a href="{{ url_for('main.movies')}}" title="Movies">Movies /</a>
  </li>
  <li class="vd-prelist">
    <a
      href="{{ url_for('main.description', movie_title=movie.movie_title|urlencode) }}"
      title="{{ movie.movie_title }}"
    >
      {{ movie.movie_title }}
    </a>
  </li>
</div>
<div class="videoplay">
  <video width="1200px" height="600px" controls>
    <source src="{{ url_for('static', filename = path) }}" type="video/mp4" />
    Trình duyệt của bạn không hỗ trợ thẻ video.
  </video>
</div>
<br />
<div class="grid">
  <section class="film-area">
    <div class="film-area__header">
      <h2 class="film-area__title">You may also like</h2>
      <div class="film-area__tabs"></div>
    </div>
    <div class="grid__row">
      {% for movie in movies %}
      <div class="grid__column-8">
        <a href="" class="film">
          <div class="film__poster">
            <div class="film__quality">HD</div>
            <img
              src="{{ movie.poster_url }}"
              alt="{{ movie.movie_title }}"
              class="film__img"
            />
            <a
              href="{{ url_for('main.watching', movie_title=movie.movie_title|urlencode) }}"
              title="{{ movie.movie_title }}"
            >
              <div class="film__play">
                <i class="fa fa-play"></i>
              </div>
            </a>
          </div>
          <div class="film__details">
            <h3 class="film__name">
              <a
                href="{{ url_for('main.description', movie_title=movie.movie_title|urlencode) }}"
                class="film__link"
                title="{{ movie.movie_title }}"
              >
                {{ movie.movie_title }}
              </a>
            </h3>
            <div class="film__infor">
              <div class="film__infor--container">
                <span class="film__infor--year">
                  {% if movie.release_date %} {{
                  movie.release_date.strftime('%Y') }} {% else %} Unknown {%
                  endif %}
                </span>
                <span class="dot"></span>
                <span class="film__infor--minute">
                  {% if movie.runtime == 0 %} Unknown {% else %} {{
                  movie.runtime }} min {% endif %}
                </span>
              </div>
              <span class="film__infor--type">Movie</span>
            </div>
          </div>
        </a>
      </div>
      {% endfor %}
    </div>
  </section>
</div>

{% endblock %}

app/templates/movies.html
{% extends 'base.html' %} 
{% block head %}
<link rel="stylesheet" href="{{ url_for('static', filename = 'base.css')}}" />
<link rel="stylesheet" href="{{ url_for('static', filename = 'movie.css')}}" />
<title>Movies</title>
{% endblock %} 

{% block content %}
<br />
<div class="grid">
  <section class="film-area">
    <div class="film-area__header">
      <h2 class="film-area__title">Movies</h2>
      <div class="film-area__tabs"></div>
    </div>
    <div class="grid__row">
      {% for movie in movies %}
      <div class="grid__column-8">
        <a href="" class="film">
          <div class="film__poster">
            <div class="film__quality">HD</div>
            <img src="{{ movie.poster_url }}" alt="{{ movie.movie_title }}" class="film__img" />
            <a href="{{ url_for('main.watching', movie_title=movie.movie_title|urlencode) }}"
              title="{{ movie.movie_title }}">
              <div class="film__play">
                <i class="fa fa-play"></i>
              </div>
            </a>
          </div>
          <div class="film__details">
            <h3 class="film__name">
              <a href="{{ url_for('main.description', movie_title=movie.movie_title|urlencode) }}"
                class="film__link" title="{{ movie.movie_title }}">
                {{ movie.movie_title }}
              </a>
            </h3>
            <div class="film__infor">
              <div class="film__infor--container">
                <span class="film__infor--year">
                  {% if movie.release_date %} {{
                  movie.release_date.strftime('%Y') }} {% else %} Unknown {%
                  endif %}
                </span>
                <span class="dot"></span>
                <span class="film__infor--minute">
                  {% if movie.runtime == 0 %} Unknown {% else %} {{
                  movie.runtime }} min {% endif %}
                </span>
              </div>
              <span class="film__infor--type">Movie</span>
            </div>
          </div>
        </a>
      </div>
      {% endfor %}
    </div>
  </section>
</div>
<div class="pagination">
  {% if prev %}
  <a class="pagination_btn" href="{{ url_for('main.movies', page = prevPage) }}">Previous</a>
  {% endif %} {% for page in range(start, end) %}
  <a href="{{ url_for('main.movies', page = page) }}" class="{% if page == curPage %}active{% endif %} pagination_btn">
    {{ page }}
  </a>
  {% endfor %} {% if next %}
  <a class="pagination_btn" href="{{ url_for('main.movies', page = nextPage) }}">Next</a>
  {% endif %}
</div>

{% endblock %}

app/templates/results.html
{% extends 'base.html' %}

{% block head %}
<link rel="stylesheet" href="{{ url_for('static', filename = 'home.css')}}" />
<title>Search Results</title>
{% endblock %}

{% block content %}
<br>
<div class="grid">
    <section class="film-area">
        <div class="film-area__header">
            <h2 class="film-area__title">Movies</h2>
            <div class="film-area__tabs"></div>
        </div>
        <div class="grid__row">
            {% for movie in list %}
            <div class="grid__column-8">
                <a href="" class="film">
                    <div class="film__poster">
                        <div class="film__quality">HD</div>
                        <img src="{{ movie.poster_url }}" alt="{{ movie.movie_title }}" class="film__img" />
                        <a href="{{ url_for('main.watching', movie_title=movie.movie_title|urlencode) }}"
              title="{{ movie.movie_title }}">
              <div class="film__play">
                <i class="fa fa-play"></i>
              </div>
            </a>
          </div>
          <div class="film__details">
            <h3 class="film__name">
              <a href="{{ url_for('main.description', movie_title=movie.movie_title|urlencode) }}"
                class="film__link" title="{{ movie.movie_title }}">
                                {{ movie.movie_title }}
                            </a>
                        </h3>
                        <div class="film__infor">
                            <div class="film__infor--container">
                                <span class="film__infor--year">
                                    {% if movie.release_date %}
                                    {{ movie.release_date.strftime('%Y') }}
                                    {% else %}
                                    Unknown
                                    {% endif %}
                                </span>
                                <span class="dot"></span>
                                <span class="film__infor--minute">
                                    {% if movie.runtime == 0 %}
                                    Unknown
                                    {% else %}
                                    {{ movie.runtime }} min
                                    {% endif %}
                                </span>
                            </div>
                            <span class="film__infor--type">Movie</span>
                        </div>
                    </div>
                </a>
            </div>
            {% endfor %}
        </div>
    </section>
</div>
{% endblock %}